networks:
    traefik:
        external: true
services:
    maki-upload:
        build: .
        restart: always
        # user: 1000:1000
        volumes:
            - ./public:/public
        # environment:
        #     PORT: 8080
        #     PUBLIC_DIR: /public
        #     TOKENS: token_a,token_b
        env_file: .env
        labels:
            - traefik.enable=true
            - traefik.http.routers.maki-upload.rule=(Host("maki.cafe") || Host("makidoll.io") || Host("hotmilk.space")) && PathPrefix("/u")
            - traefik.http.routers.maki-upload.entrypoints=websecure
            - traefik.http.routers.maki-upload.service=maki-upload
            - traefik.http.routers.maki-upload.priority=99999
            - traefik.http.routers.maki-upload.tls.certResolver=le
            - traefik.http.services.maki-upload.loadbalancer.server.port=8080
            - traefik.docker.network=traefik
        networks:
            - default
            - traefik
